---
server:
  port: ${APP_PORT:8000}
---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/barcodes
---
short-link: http://localhost:${APP_PORT:8000}/api/v1/barcodes/redirect
---
spring:
  cache:
    type: redis
  redis:
    host: ${HOST_CACHE:localhost}
    port: 6379
    connect-timeout: 30s