version: "3.1"
services:
  redis:
    restart: always
    container_name: redis-server
    image: "redis"
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"